services:
  version: '3'
  # spark-master:
  # image: spark:python3
  spark-interactive:
    image: spark:python3
    # environment: 
    # - SPARK_DRIVER_BIND_ADDRESS: spark-master
    command: /opt/spark/bin/pyspark
