services:
  pismo-data:
    build: ./data/
    volumes:
      - ./data/:/app/
      - pismo-data:/data

  pismo-app:
    depends_on:
      pismo-data:
        condition: service_completed_successfully
    build: .
    ports:
      - "4040:4040"
    environment:
      - SPARK_MASTER=local[*]
    volumes:
      - pismo-data:/data/
      - ./output/:/output/
      - ./pismo.py:/app/pismo.py

volumes:
  pismo-data:
