services:
  hadoop-namenode:
    image: apache/hadoop:3
    command: [ "hdfs", "namenode" ]
    ports:
      - 9870:9870
    env_file:
      - ./hadoop_config
    environment:
        ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
  hadoop-datanode:
    image: apache/hadoop:3
    command: ["hdfs", "datanode"]
    env_file:
      - ./hadoop_config      
  hadoop-resourcemanager:
    image: apache/hadoop:3
    command: ["yarn", "resourcemanager"]
    ports:
       - 8088:8088
    env_file:
      - ./hadoop_config
    volumes:
      - ./test.sh:/opt/test.sh
  hadoop-nodemanager:
    image: apache/hadoop:3
    command: ["yarn", "nodemanager"]
    env_file:
      - ./hadoop_config


  ####### SPARK
  #
  spark-master:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - 7077:7077
      - 8080:8080
    volumes:
      - ./app/:/opt/workspace

  spark-worker-0:
    image: docker.io/bitnami/spark:3.5
    ports:
      - 8081:8081
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ./app/:/opt/workspace
