services:
  hadoop-namenode:
    image: apache/hadoop:3
    command: [ "hdfs", "namenode" ]
    ports:
      - 9870:9870
    env_file:
      - ./hadoop_config
    environment:
        ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
  hadoop-datanode:
    image: apache/hadoop:3
    command: ["hdfs", "datanode"]
    env_file:
      - ./hadoop_config      
  hadoop-resourcemanager:
    image: apache/hadoop:3
    command: ["yarn", "resourcemanager"]
    ports:
       - 8088:8088
    env_file:
      - ./hadoop_config
    volumes:
      - ./test.sh:/opt/test.sh
  hadoop-nodemanager:
    image: apache/hadoop:3
    command: ["yarn", "nodemanager"]
    env_file:
      - ./hadoop_config


